#pragma once

#define RX_DIR_DELIMETER '/'
#define RX_OBJECT_DELIMETER '.'
#define RX_DIR_OBJECT_DELIMETER '/'
#define RX_PATH_CURRENT '.'
#define RX_PATH_PARENT '#'
#define RX_SOURCE_DELIMETER '#'
#define RX_DIR_DELIMETER_STR "/"
#define RX_OBJECT_DELIMETER_STR "."
#define RX_DIR_OBJECT_DELIMETER_STR "/"
#define RX_PATH_CURRENT_STR "."
#define RX_PATH_PARENT_STR '$'
#define RX_DEFAULT_VARIABLE_NAME "_"
#define RX_SOURCE_DELIMETER_STR "#"
#define RX_MACRO_SYMBOL '$'
#define RX_MACRO_SYMBOL_STR "$"

#define RX_LINE_END "\n"
#define RX_LINE_END_CH '\n'

// directories stuff
#define RX_NS_WORLD_NAME "world"
#define RX_NS_STORAGE_NAME "storage"
#define RX_NS_SYS_NAME "sys"
#define RX_NS_TEST_NAME "test"
#define RX_NS_UNASSIGNED_NAME "unassigned"
#define RX_NS_BIN_NAME "bin"
#define RX_NS_OBJ_NAME "runtime"
#define RX_NS_SYSTEM_OBJ_NAME "system"
#define RX_NS_PORT_OBJ_NAME "ports"
#define RX_NS_RELATIONS_NAME "relations"
#define RX_NS_CLASSES_NAME "types"
#define RX_NS_BASE_CLASSES_NAME "base"
#define RX_NS_SYSTEM_CLASSES_NAME "system"
#define RX_NS_PORT_CLASSES_NAME "ports"
#define RX_NS_SUPPORT_CLASSES_NAME "support"
#define RX_NS_SIMULATION_CLASSES_NAME "simulation"
#define RX_NS_PLUGINS_NAME "plugins"
#define RX_NS_HOST_NAME "host"

#define RX_NULL_ITEM_NAME "<nullptr>"

// basic classes
#define RX_CLASS_OBJECT_BASE_NAME "ObjectBase"
#define RX_CLASS_OBJECT_BASE_ID 0x00000001
#define RX_CLASS_DOMAIN_BASE_NAME "DomainBase"
#define RX_CLASS_DOMAIN_BASE_ID 0x00000002
#define RX_CLASS_APPLICATION_BASE_NAME "ApplicationBase"
#define RX_CLASS_APPLICATION_BASE_ID 0x00000003
#define RX_CLASS_PORT_BASE_NAME "PortBase"
#define RX_CLASS_PORT_BASE_ID 0x00000004

#define RX_CLASS_STRUCT_BASE_NAME "StructBase"
#define RX_CLASS_STRUCT_BASE_ID 0x00000005
#define RX_CLASS_VARIABLE_BASE_NAME "VariableBase"
#define RX_CLASS_VARIABLE_BASE_ID 0x00000006
#define RX_CLASS_EVENT_BASE_NAME "EventBase"
#define RX_CLASS_EVENT_BASE_ID 0x00000007
#define RX_CLASS_SOURCE_BASE_NAME "SourceBase"
#define RX_CLASS_SOURCE_BASE_ID 0x00000008
#define RX_CLASS_MAPPER_BASE_NAME "MapperBase"
#define RX_CLASS_MAPPER_BASE_ID 0x00000009
#define RX_CLASS_FILTER_BASE_NAME "FilterBase"
#define RX_CLASS_FILTER_BASE_ID 0x0000000a


#define RX_CLASS_METHOD_BASE_NAME "MethodBase"
#define RX_CLASS_METHOD_BASE_ID 0x00000013
#define RX_CLASS_PROGRAM_BASE_NAME "ProgramBase"
#define RX_CLASS_PROGRAM_BASE_ID 0x00000014
#define RX_CLASS_DATA_BASE_NAME "DataTypeBase"
#define RX_CLASS_DATA_BASE_ID 0x00000015
#define RX_CLASS_DISPLAY_BASE_NAME "DisplayBase"
#define RX_CLASS_DISPLAY_BASE_ID 0x00000016


// objects stuff
#define RX_NS_SYSTEM_APP_NAME "SystemApp"
#define RX_NS_SYSTEM_APP_ID 0x0000000b
#define RX_NS_SYSTEM_DOM_NAME "SystemDomain"
#define RX_NS_SYSTEM_DOM_ID 0x0000000c
#define RX_NS_OBJECT_DATA_NAME "ObjectData"
#define RX_NS_OBJECT_DATA_ID 0x0000000d


#define RX_HOST_OBJ_ID 0xc00006f
#define RX_HOST_APP_ID 0xc000070
#define RX_HOST_DOMAIN_ID 0xc000071

#define RX_HOST_APP_NAME "HostApp"
#define RX_HOST_DOMAIN_NAME "HostDomain"
#define RX_HOST_OBJECT_NAME "Host"


#define RX_NS_RELATION_BASE_NAME "RelationBase"
#define RX_NS_RELATION_BASE_ID 0x0000000e

#define RX_NS_PORT_STACK_NAME "PortStack"
#define RX_NS_PORT_STACK_ID 0x0000000f

#define RX_NS_PORT_REF_NAME "PortReference"
#define RX_NS_PORT_REF_ID 0x00000017

#define RX_NS_APPLICATION_RELATION_NAME "Application"
#define RX_NS_APPLICATION_RELATION_ID 0x00000010

#define RX_NS_PORT_APPLICATION_RELATION_NAME "PortApp"
#define RX_NS_PORT_APPLICATION_RELATION_ID 0x00000011

#define RX_NS_DOMAIN_RELATION_NAME "Domain"
#define RX_NS_DOMAIN_RELATION_ID 0x00000012

#define NS_RX_COMMANDS_MANAGER_NAME "CmdManager"
#define RX_COMMANDS_MANAGER_ID 0x8000001

#define RX_NS_SERVER_RT_NAME "Runtime"
#define RX_NS_SERVER_RT_ID 0x8000002
#define RX_IO_MANAGER_NAME "IoManager"
#define RX_IO_MANAGER_ID 0x8000003


#define IO_POOL_NAME "IoPool"
#define IO_POOL_ID 0x8000004
#define UNASSIGNED_POOL_NAME "UnassignedPool"
#define UNASSIGNED_POOL_ID 0x8000005
#define WORKER_POOL_NAME "WorkerPool"
#define WORKER_POOL_ID 0x8000006
#define IO_LOG_NAME "Log"
#define IO_LOG_ID 0x8000007

#define RX_NS_SYSTEM_UNASS_NAME "UnassignedDomain"
#define RX_NS_SYSTEM_UNASS_ID 0x8000009
#define RX_NS_SYSTEM_UNASS_APP_NAME "UnassignedApp"
#define RX_NS_SYSTEM_UNASS_APP_ID 0x800000a
#define RX_NS_SYSTEM_UNASS_APP_PATH RX_DIR_DELIMETER_STR RX_NS_UNASSIGNED_NAME RX_DIR_DELIMETER_STR RX_NS_SYSTEM_UNASS_APP_NAME

#define META_POOL_NAME "MetaPool"
#define META_POOL_ID 0x8000019
#define RX_NS_SYSTEM_NAME "System"
#define RX_NS_SYSTEM_ID 0x800001a

// system objects type stuff
#define RX_NS_SYSTEM_APP_TYPE_NAME "SysAppType"
#define RX_NS_SYSTEM_APP_TYPE_ID 0xc000000

#define RX_NS_SYSTEM_TYPE_NAME "SystemType"
#define RX_NS_SYSTEM_TYPE_ID 0xc000054
#define RX_NS_SYSTEM_INFO_TYPE_NAME "SystemInfo"
#define RX_NS_SYSTEM_INFO_TYPE_ID 0xc000055
#define RX_NS_SYSTEM_DOM_TYPE_NAME "SysDomainType"
#define RX_NS_SYSTEM_DOM_TYPE_ID 0xc000001


#define RX_USER_APP_TYPE_NAME "UserApplication"
#define RX_USER_APP_TYPE_ID 0xc00003a
#define RX_USER_DOMAIN_TYPE_NAME "UserDomain"
#define RX_USER_DOMAIN_TYPE_ID 0xc00003b
#define RX_USER_OBJECT_TYPE_NAME "UserObject"
#define RX_USER_OBJECT_TYPE_ID 0xc00003c

#define RX_HOST_APP_TYPE_NAME "HostApplicationType"
#define RX_HOST_APP_TYPE_ID 0xc00004b
#define RX_HOST_DOMAIN_TYPE_NAME "HostDomainType"
#define RX_HOST_DOMAIN_TYPE_ID 0xc00004c
#define RX_NS_HOST_INFO_NAME "HostInfo"
#define RX_NS_HOST_INFO_ID 0xc000056
#define RX_NS_HOST_TYPE_NAME "HostType"
#define RX_NS_HOST_TYPE_ID 0xc000057


#define RX_INTERNAL_APP_TYPE_NAME "InternalAppType"
#define RX_INTERNAL_APP_TYPE_ID 0xc00003d
#define RX_INTERNAL_DOMAIN_TYPE_NAME "InternalDomainType"
#define RX_INTERNAL_DOMAIN_TYPE_ID 0xc00003e
#define RX_INTERNAL_OBJECT_TYPE_NAME "InternalObjectType"
#define RX_INTERNAL_OBJECT_TYPE_ID 0xc00003f

#define RX_COMMANDS_MANAGER_TYPE_NAME "CmdManagerType"
#define RX_COMMANDS_MANAGER_TYPE_ID 0xc000002
#define RX_CONSOLE_TYPE_NAME "ConsolePort"
#define RX_CONSOLE_TYPE_ID 0xc000003


#define RX_NS_SERVER_RT_TYPE_NAME "RuntimeType"
#define RX_NS_SERVER_RT_TYPE_ID 0xc000004
#define RX_IO_MANAGER_TYPE_NAME "IoManagerType"
#define RX_IO_MANAGER_TYPE_ID 0xc000005

#define RX_POOL_TYPE_NAME "IoPoolType"
#define RX_POOL_TYPE_ID 0xc000007
#define RX_LOG_TYPE_NAME "LogType"
#define RX_LOG_TYPE_ID 0xc000009
#define RX_NS_SYSTEM_UNASS_TYPE_NAME "UnassignedDomainType"
#define RX_NS_SYSTEM_UNASS_TYPE_ID 0xc00000a
#define RX_NS_SYSTEM_UNASS_APP_TYPE_NAME "UnassignedAppType"
#define RX_NS_SYSTEM_UNASS_APP_TYPE_ID 0xc00000b



// port classes and related structs
#define RX_EXTERNAL_PORT_TYPE_NAME "ExternalPort"
#define RX_EXTERNAL_PORT_TYPE_ID 0xc00000c
//#define RX_PHYSICAL_SINGLE_PORT_TYPE_NAME "PhysicalSingle"
//#define RX_PHYSICAL_SINGLE_PORT_TYPE_ID 0xc000036
//#define RX_PHYSICAL_MULTI_PORT_TYPE_NAME "PhysicalMultiple"
//#define RX_PHYSICAL_MULTI_PORT_TYPE_ID 0xc000037

#define RX_TRANSPORT_PORT_TYPE_NAME "TransportPort"
#define RX_TRANSPORT_PORT_TYPE_ID 0xc00000d
#define RX_ROUTED_TRANSPORT_PORT_TYPE_NAME "RoutedTransportPort"
#define RX_ROUTED_TRANSPORT_PORT_TYPE_ID 0xc000038

#define RX_APPLICATION_PORT_TYPE_NAME "ApplicationPort"
#define RX_APPLICATION_PORT_TYPE_ID 0xc00000e

#define RX_SERIAL_PORT_TYPE_NAME "SerialPort"
#define RX_SERIAL_PORT_TYPE_ID 0xc000010
#define RX_UDP_PORT_TYPE_NAME "UDPPort"
#define RX_UDP_PORT_TYPE_ID 0xc000011
#define RX_TCP_SERVER_PORT_TYPE_NAME "TCPServerPort"
#define RX_TCP_SERVER_PORT_TYPE_ID 0xc000014
#define RX_TCP_CLIENT_PORT_TYPE_NAME "TCPClientPort"
#define RX_TCP_CLIENT_PORT_TYPE_ID 0xc000015
#define RX_ETHERNET_PORT_TYPE_NAME "EthernetPort"
#define RX_ETHENERT_PORT_TYPE_ID 0xc000016


#define RX_IP4_ROUTER_TYPE_NAME "IP4RouterPort"
#define RX_IP4_ROUTER_TYPE_ID 0xc00005a
#define RX_BYTE_ROUTER_TYPE_NAME "ByteRouterPort"
#define RX_BYTE_ROUTER_TYPE_ID 0xc00005b

#define RX_TRANS_LIMITER_TYPE_NAME "TransactionLimiterPort"
#define RX_TRANS_LIMITER_TYPE_ID 0xc00005c

#define RX_INITIATOR_TO_LISTENER_PORT_TYPE_NAME "Initiator2ListenerPort"
#define RX_INITIATOR_TO_LISTENER_PORT_TYPE_ID 0xc00006c
#define RX_LISTENER_TO_INITIATOR_PORT_TYPE_NAME "Listener2InitiatorPort"
#define RX_LISTENER_TO_INITIATOR_PORT_TYPE_ID 0xc00006d

#define RX_STXETX_TYPE_NAME "STXETXPort"
#define RX_STXETX_TYPE_ID 0xc00006a

#define RX_VT00_TYPE_NAME "VT100Port"
#define RX_VT00_TYPE_ID 0xc000017

#define RX_TELNET_TYPE_NAME "TelnetPort"
#define RX_TELNET_TYPE_ID 0xc000018


#define RX_PORT_STATUS_TYPE_NAME "PortStatusData"
#define RX_PORT_STATUS_TYPE_ID 0xc000019
#define RX_PHY_PORT_STATUS_TYPE_NAME "ExternalPortStatusData"
#define RX_PHY_PORT_STATUS_TYPE_ID 0xc000020
#define RX_CLIENT_PORT_STATUS_TYPE_NAME "ClientPortStatusData"
#define RX_CLIENT_PORT_STATUS_TYPE_ID 0xc00005e
#define RX_MASTER_PORT_STATUS_TYPE_NAME "MasterPortStatusData"
#define RX_MASTER_PORT_STATUS_TYPE_ID 0xc00005f

#define RX_IP_BIND_TYPE_NAME "IPBindData"
#define RX_IP_BIND_TYPE_ID 0xc000021


#define RX_RX_JSON_TYPE_NAME "RxJsonProtocol"
#define RX_RX_JSON_TYPE_ID 0xc000022

#define RX_TIMEOUTS_TYPE_NAME "TimeoutsData"
#define RX_TIMEOUTS_TYPE_ID 0xc000024
#define RX_CLIENT_TIMEOUTS_TYPE_NAME "ClientTimeoutsData"
#define RX_CLIENT_TIMEOUTS_TYPE_ID 0xc000025
#define RX_SERVER_TIMEOUTS_TYPE_NAME "ServerTimeoutsData"
#define RX_SERVER_TIMEOUTS_TYPE_ID 0xc000060
#define RX_MASTER_TIMEOUTS_TYPE_NAME "MasterTimeoutsData"
#define RX_MASTER_TIMEOUTS_TYPE_ID 0xc00005d


#define RX_PORT_OPTIONS_TYPE_NAME "PortOptions"
#define RX_PORT_OPTIONS_TYPE_ID 0xc000061
#define RX_ROUTER_PORT_OPTIONS_TYPE_NAME "RouterPortOptions"
#define RX_ROUTER_PORT_OPTIONS_TYPE_ID 0xc000062
#define RX_BRIDGE_PORT_OPTIONS_TYPE_NAME "BridgePortOptions"
#define RX_BRIDGE_PORT_OPTIONS_TYPE_ID 0xc000063
#define RX_LIMITER_PORT_OPTIONS_TYPE_NAME "LimiterPortOptions"
#define RX_LIMITER_PORT_OPTIONS_TYPE_ID 0xc000064


#define RX_STXETX_PORT_OPTIONS_TYPE_NAME "STXETXPortOptions"
#define RX_STXETX_PORT_OPTIONS_TYPE_ID 0xc00006e


#define RX_SERIAL_PORT_OPTIONS_TYPE_NAME "SerialPortOptions"
#define RX_SERIAL_PORT_OPTIONS_TYPE_ID 0xc00006b

// runtime support structures
#define RX_POOL_DATA_TYPE_NAME "PoolData"
#define RX_POOL_DATA_TYPE_ID 0xc000026
#define RX_RT_DATA_TYPE_NAME "RuntimeData"
#define RX_RT_DATA_TYPE_ID 0xc000027


#define RX_UNASSIGNED_POOL_TYPE_NAME "UnassignedThreadType"
#define RX_UNASSIGNED_POOL_TYPE_ID 0xc000028
#define RX_META_POOL_TYPE_NAME "MetaThreadType"
#define RX_META_POOL_TYPE_ID 0xc000029

#define RX_THREAD_DATA_TYPE_NAME "ThreadData"
#define RX_THREAD_DATA_TYPE_ID 0xc000030
#define RX_PHYSICAL_THREAD_TYPE_NAME "PhysicalThread"
#define RX_PHYSICAL_THREAD_TYPE_ID 0xc000031


#define RX_OPCUA_TRANSPORT_PORT_TYPE_NAME "OPCUATransport"
#define RX_OPCUA_TRANSPORT_PORT_TYPE_ID 0xc000032


#define RX_EXTERN_MAPPER_TYPE_NAME "ExternMapper"
#define RX_EXTERN_MAPPER_TYPE_ID 0xc000033
#define RX_PARENT_MAPPER_TYPE_NAME "ParentMapper"
#define RX_PARENT_MAPPER_TYPE_ID 0xc000045
#define RX_EXTERN_PARENT_MAPPER_TYPE_NAME "ExternParentMapper"
#define RX_EXTERN_PARENT_MAPPER_TYPE_ID 0xc00004d
#define RX_SYSTEM_MAPPER_TYPE_NAME "SystemMapper"
#define RX_SYSTEM_MAPPER_TYPE_ID 0xc000046
#define RX_EXTERN_SOURCE_TYPE_NAME "ExternSource"
#define RX_EXTERN_SOURCE_TYPE_ID 0xc000034
#define RX_USER_SOURCE_TYPE_NAME "UserSource"
#define RX_USER_SOURCE_TYPE_ID 0xc00004a
#define RX_PARENT_SOURCE_TYPE_NAME "ParentSource"
#define RX_PARENT_SOURCE_TYPE_ID 0xc000047
#define RX_EXTERN_PARENT_SOURCE_TYPE_NAME "ExternParentSource"
#define RX_EXTERN_PARENT_SOURCE_TYPE_ID 0xc00004e
#define RX_SYSTEM_SOURCE_TYPE_NAME "SystemSource"
#define RX_SYSTEM_SOURCE_TYPE_ID 0xc000048
#define RX_REGISTER_SOURCE_TYPE_NAME "RegisterSource"
#define RX_REGISTER_SOURCE_TYPE_ID 0xc000035
#define RX_REGISTER_VARIABLE_TYPE_NAME "RegisterVariable"
#define RX_REGISTER_VARIABLE_TYPE_ID 0xc000069
#define RX_PLATFORM_SOURCE_TYPE_NAME "PlatformSource"
#define RX_PLATFORM_SOURCE_TYPE_ID 0xc000049
 

#define RX_LINEAR_SCALING_FILTER_TYPE_NAME "LinearScaling"
#define RX_LINEAR_SCALING_FILTER_TYPE_ID 0xc000039
#define RX_LIMIT_FILTER_TYPE_NAME "LimitFilter"
#define RX_LIMIT_FILTER_TYPE_ID 0xc000065
#define RX_CUTOFF_FILTER_TYPE_NAME "CutoffScaling"
#define RX_CUTOFF_FILTER_TYPE_ID 0xc000066
#define RX_LO_CUTOFF_FILTER_TYPE_NAME "LowCutoffScaling"
#define RX_LO_CUTOFF_FILTER_TYPE_ID 0xc000067
#define RX_HI_CUTOFF_FILTER_TYPE_NAME "HighCutoffScaling"
#define RX_HI_CUTOFF_FILTER_TYPE_ID 0xc000068

#define RX_SIMULATION_SOURCE_TYPE_NAME "SimulationSource"
#define RX_SIMULATION_SOURCE_TYPE_ID 0xc000040
#define RX_RAMP_SIMULATION_SOURCE_TYPE_NAME "RampSource"
#define RX_RAMP_SIMULATION_SOURCE_TYPE_ID 0xc000041
#define RX_SINE_SIMULATION_SOURCE_TYPE_NAME "SineSource"
#define RX_SINE_SIMULATION_SOURCE_TYPE_ID 0xc000041


#define RX_NS_SYSTEM_TCP_NAME "TcpServer"
#define RX_NS_SYSTEM_TCP_ID 0xc000042
#define RX_NS_SYSTEM_OPCUABIN_NAME "OpcUaTransport"
#define RX_NS_SYSTEM_OPCUABIN_ID 0xc000043
#define RX_NS_SYSTEM_RXJSON_NAME "JSON"
#define RX_NS_SYSTEM_RXJSON_ID 0xc000044


#define RX_NS_CHANGED_DATA_NAME "ItemChangeDetails"
#define RX_NS_CHANGED_DATA_ID 0xc00004f
#define RX_NS_CHANGED_DATA_EVENT_NAME "ItemChangeEvent"
#define RX_NS_CHANGED_DATA_EVENT_ID 0xc000050


#define RX_NS_HTTP_TYPE_NAME "HttpProtocol"
#define RX_NS_HTTP_TYPE_ID 0xc000051

#define RX_NS_HTTP_TCP_NAME "TcpHttp"
#define RX_NS_HTTP_TCP_ID 0xc000052

#define RX_NS_HTTP_NAME "Http"
#define RX_NS_HTTP_ID 0xc000053


#define RX_TCP_HTTP_PORT_TYPE_ID 0xc000058
#define RX_TCP_HTTP_PORT_TYPE_NAME "SystemHttpPort"
#define RX_TCP_RX_PORT_TYPE_ID 0xc000059
#define RX_TCP_RX_PORT_TYPE_NAME "SystemRxPort"


// last is 0xc000071!!!! 

// cpp classes stuff
#define RX_CPP_OBJECT_CLASS_TYPE_NAME "object_type"
#define RX_CPP_OBJECT_TYPE_NAME "object"
#define RX_CPP_OBJECT_TYPE_ID "object"
#define RX_CPP_DOMAIN_CLASS_TYPE_NAME "domain_type"
#define RX_CPP_DOMAIN_TYPE_NAME "domain"
#define RX_CPP_APPLICATION_CLASS_TYPE_NAME "application_type"
#define RX_CPP_APPLICATION_TYPE_NAME "application"
#define RX_CPP_PORT_CLASS_TYPE_NAME "port_type"
#define RX_CPP_PORT_TYPE_NAME "port"
#define RX_TEST_CASE_TYPE_NAME "test_case"

#define RX_CPP_DIRECORY_TYPE_NAME "directory"
#define RX_CPP_COMMAND_TYPE_NAME "command"

#define RX_CONST_VALUE_TYPE_NAME "const_value"
#define RX_VALUE_TYPE_NAME "value"
#define RX_INDIRECT_VALUE_TYPE_NAME "value"

#define RX_CPP_VARIABLE_CLASS_TYPE_NAME "variable_type"
#define RX_CPP_VARIABLE_TYPE_NAME "variable"
#define RX_CPP_STRUCT_CLASS_TYPE_NAME "struct_type"
#define RX_CPP_STRUCT_TYPE_NAME "struct"
#define RX_CPP_MAPPER_CLASS_TYPE_NAME "mapper_type"
#define RX_CPP_MAPPER_TYPE_NAME "mapper"
#define RX_CPP_SOURCE_CLASS_TYPE_NAME "source_type"
#define RX_CPP_SOURCE_TYPE_NAME "source"
#define RX_CPP_FILTER_CLASS_TYPE_NAME "filter_type"
#define RX_CPP_FILTER_TYPE_NAME "filter"
#define RX_CPP_EVENT_CLASS_TYPE_NAME "event_type"
#define RX_CPP_EVENT_TYPE_NAME "event"
#define RX_CPP_RELATION_CLASS_TYPE_NAME "relation_type"
#define RX_CPP_RELATION_TYPE_NAME "relation"
#define RX_CPP_RELATION_TARGET_TYPE_NAME "relation_target"

#define RX_CPP_METHOD_CLASS_TYPE_NAME "method_type"
#define RX_CPP_METHOD_TYPE_NAME "method"
#define RX_CPP_PROGRAM_CLASS_TYPE_NAME "program_type"
#define RX_CPP_PROGRAM_TYPE_NAME "program"
#define RX_CPP_DATA_CLASS_TYPE_NAME "data_type"
#define RX_CPP_DATA_TYPE_NAME "data"
#define RX_CPP_DISPLAY_CLASS_TYPE_NAME "display_type"
#define RX_CPP_DISPLAY_TYPE_NAME "display"

//Main messages
#define RX_ACCESS_DENIED "*ACCESS DENIED*"

// Console related stuff
#define RX_CONSOLE_HEADER_LINE "============================================="


//Testing related stuff
#define RX_TEST_STATUS_UNKNOWN 0
#define RX_TEST_STATUS_OK 1
#define RX_TEST_STATUS_FAILED 2


#define RX_TEST_STATUS_UNKNOWN_NAME RX_NULL_ITEM_NAME
#define RX_TEST_STATUS_OK_NAME "Passed"
#define RX_TEST_STATUS_FAILED_NAME "*FAILED*"

//Storage related stuff
#define RX_FILE_STORAGE_FOLDER "storage"

