
/****************************************************************************
* This file is automatically generated by <opcgen-nodes> tool
*
* Generated at:6/17/2022 10:56 AM
*
****************************************************************************/

#include "rx_opcua_std.h"

namespace protocols {
namespace opcua {
namespace opcua_addr_space {

class opcua_std_address_space_builder
{
public:
	static rx_result build_standard_address_space_UANodeSet2(opcua_std_address_space&server);
private:
	static rx_result resolve_standard_address_space_references(opcua_std_address_space& server);
	static rx_result resolve_references_collection(node_references::references_type& col, opcua_std_address_space& server);
};

} //namespace protocols
} //namespace opcua
} //namespace opcua_addr_space
