
/****************************************************************************
* This file is automatically generated by <opcgen-nodes> tool
*
* Generated at:1/12/2023 5:44 PM
*
****************************************************************************/

#include "rx_opcua_std.h"

namespace protocols {
namespace opcua {
namespace opcua_addr_space {

class opcua_std_address_space_builder
{
public:
	static rx_result build_standard_address_space_UANodeSet2(opcua_std_address_space&server);
	static rx_result resolve_references_collection(node_references::references_type& col, const reference_data_argument_t& data, opcua_std_address_space& server);
};

} //namespace protocols
} //namespace opcua
} //namespace opcua_addr_space
