
/****************************************************************************
* This file is automatically generated by <opcgen-nodes> tool
*
* Generated at:1/12/2023 5:44 PM
*
****************************************************************************/


#include "pch.h"
#include "rx_opcua_build_nodes2.h"

namespace protocols {
namespace opcua {
namespace opcua_addr_space {


const uintptr_t valued_idx_mask = 0x80000000;
const uintptr_t idx_value_mask = 0x0fffffff;
const uintptr_t invalid_idx = 0xffffffff;

rx_result opcua_std_address_space_builder::resolve_references_collection(node_references::references_type& col, const reference_data_argument_t& data, opcua_std_address_space& server)
{
	size_t i=0;
	for (auto& one_ref : col)
	{
		uint32_t idx = data.data[i].target_idx;
		if (idx != invalid_idx)
		{
			if (idx & valued_idx_mask)
			{
				idx &= idx_value_mask;
				RX_ASSERT(idx < server.registered_valued_nodes_.size());
				one_ref.resolved_node = server.registered_valued_nodes_[idx];
			}
			else
			{
				RX_ASSERT(idx < server.registered_nodes_.size());
				one_ref.resolved_node = server.registered_nodes_[idx];
			}
		}
		i++;
	}
	return true;
}


} //namespace protocols
} //namespace opcua
} //namespace opcua_addr_space

