

/****************************************************************************
*
*  system\runtime\rx_rt_items3.cpp
*
*  Copyright (c) 2020-2023 ENSACO Solutions doo
*  Copyright (c) 2018-2019 Dusan Ciric
*
*  
*  This file is part of {rx-platform} 
*
*  
*  {rx-platform} is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*  
*  {rx-platform} is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*  
*  You should have received a copy of the GNU General Public License  
*  along with {rx-platform}. It is also available in any {rx-platform} console
*  via <license> command. If not, see <http://www.gnu.org/licenses/>.
*  
****************************************************************************/


#include "pch.h"



#include "system/runtime/rx_rt_item_types.cpp"

namespace rx_platform {
namespace runtime {
namespace structure {

//*********************************************************************************************************
//*                      CODE GENERATED BY GenerateRuntimeItemBoringStuff tool!!!                         *
//*********************************************************************************************************
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x80>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x81>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x82>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x83>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x84>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x85>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x86>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x87>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x88>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x89>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x8a>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x8b>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x8c>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x8d>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x8e>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x8f>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x90>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x91>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x92>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x93>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x94>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x95>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x96>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x97>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x98>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x99>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x9a>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x9b>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x9c>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x9d>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x9e>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0x9f>;
//*********************************************************************************************************





} // namespace structure
} // namespace runtime
} // namespace rx_platform

