

/****************************************************************************
*
*  system\runtime\rx_rt_items2.cpp
*
*  Copyright (c) 2020-2023 ENSACO Solutions doo
*  Copyright (c) 2018-2019 Dusan Ciric
*
*  
*  This file is part of {rx-platform} 
*
*  
*  {rx-platform} is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*  
*  {rx-platform} is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*  
*  You should have received a copy of the GNU General Public License  
*  along with {rx-platform}. It is also available in any {rx-platform} console
*  via <license> command. If not, see <http://www.gnu.org/licenses/>.
*  
****************************************************************************/


#include "pch.h"



#include "system/runtime/rx_rt_item_types.cpp"

namespace rx_platform {
namespace runtime {
namespace structure {


//*********************************************************************************************************
//*                      CODE GENERATED BY GenerateRuntimeItemBoringStuff tool!!!                         *
//*********************************************************************************************************
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x40>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x41>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x42>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x43>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x44>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x45>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x46>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x47>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x48>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x49>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x4a>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x4b>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x4c>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x4d>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x4e>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x4f>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x50>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x51>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x52>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x53>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x54>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x55>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x56>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x57>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x58>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x59>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x5a>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x5b>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x5c>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x5d>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x5e>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x5f>;




} // namespace structure
} // namespace runtime
} // namespace rx_platform

