

/****************************************************************************
*
*  system\runtime\rx_rt_items5.cpp
*
*  Copyright (c) 2020-2023 ENSACO Solutions doo
*  Copyright (c) 2018-2019 Dusan Ciric
*
*  
*  This file is part of {rx-platform} 
*
*  
*  {rx-platform} is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*  
*  {rx-platform} is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*  
*  You should have received a copy of the GNU General Public License  
*  along with {rx-platform}. It is also available in any {rx-platform} console
*  via <license> command. If not, see <http://www.gnu.org/licenses/>.
*  
****************************************************************************/


#include "pch.h"



#include "system/runtime/rx_rt_item_types.cpp"

namespace rx_platform {
namespace runtime {
namespace structure {

//*********************************************************************************************************
//*                      CODE GENERATED BY GenerateRuntimeItemBoringStuff tool!!!                         *
//*********************************************************************************************************
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x20>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x21>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x22>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x23>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x24>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x25>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x26>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x27>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x28>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x29>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x2a>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x2b>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x2c>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x2d>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x2e>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x2f>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x30>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x31>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x32>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x33>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x34>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x35>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x36>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x37>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x38>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x39>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x3a>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x3b>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x3c>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x3d>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x3e>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x3f>;
//*********************************************************************************************************






} // namespace structure
} // namespace runtime
} // namespace rx_platform

