

/****************************************************************************
*
*  system\runtime\rx_rt_items6.cpp
*
*  Copyright (c) 2020-2023 ENSACO Solutions doo
*  Copyright (c) 2018-2019 Dusan Ciric
*
*  
*  This file is part of {rx-platform} 
*
*  
*  {rx-platform} is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*  
*  {rx-platform} is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*  
*  You should have received a copy of the GNU General Public License  
*  along with {rx-platform}. It is also available in any {rx-platform} console
*  via <license> command. If not, see <http://www.gnu.org/licenses/>.
*  
****************************************************************************/


#include "pch.h"



#include "system/runtime/rx_rt_item_types.cpp"

namespace rx_platform {
namespace runtime {
namespace structure {


//*********************************************************************************************************
//*                      CODE GENERATED BY GenerateRuntimeItemBoringStuff tool!!!                         *
//*********************************************************************************************************
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x60>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x61>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x62>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x63>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x64>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x65>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x66>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x67>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x68>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x69>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x6a>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x6b>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x6c>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x6d>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x6e>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x6f>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x70>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x71>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x72>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x73>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x74>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x75>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x76>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x77>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x78>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x79>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x7a>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x7b>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x7c>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x7d>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x7e>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	has<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x7f>;
//*********************************************************************************************************





} // namespace structure
} // namespace runtime
} // namespace rx_platform

