

/****************************************************************************
*
*  system\runtime\rx_rt_items1.cpp
*
*  Copyright (c) 2020-2023 ENSACO Solutions doo
*  Copyright (c) 2018-2019 Dusan Ciric
*
*  
*  This file is part of {rx-platform} 
*
*  
*  {rx-platform} is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*  
*  {rx-platform} is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*  
*  You should have received a copy of the GNU General Public License  
*  along with {rx-platform}. It is also available in any {rx-platform} console
*  via <license> command. If not, see <http://www.gnu.org/licenses/>.
*  
****************************************************************************/


#include "pch.h"



#include "system/runtime/rx_rt_item_types.cpp"

namespace rx_platform {
namespace runtime {
namespace structure {

//*********************************************************************************************************
//*                      CODE GENERATED BY GenerateRuntimeItemBoringStuff tool!!!                         *
//*********************************************************************************************************
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x00>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x01>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x02>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x03>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x04>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x05>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x06>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x07>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x08>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x09>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x0a>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x0b>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x0c>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x0d>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x0e>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x0f>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x10>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x11>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x12>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x13>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x14>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x15>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x16>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x17>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x18>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x19>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x1a>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x1b>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x1c>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x1d>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x1e>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	empty<array_wrapper<value_block_data>>,
	empty<array_wrapper<variable_block_data>>,
	0x1f>;
//*********************************************************************************************************






} // namespace structure
} // namespace runtime
} // namespace rx_platform

