

/****************************************************************************
*
*  system\runtime\rx_rt_items7.cpp
*
*  Copyright (c) 2020-2023 ENSACO Solutions doo
*  Copyright (c) 2018-2019 Dusan Ciric
*
*  
*  This file is part of {rx-platform} 
*
*  
*  {rx-platform} is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*  
*  {rx-platform} is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*  
*  You should have received a copy of the GNU General Public License  
*  along with {rx-platform}. It is also available in any {rx-platform} console
*  via <license> command. If not, see <http://www.gnu.org/licenses/>.
*  
****************************************************************************/


#include "pch.h"



#include "system/runtime/rx_rt_item_types.cpp"

namespace rx_platform {
namespace runtime {
namespace structure {

//*********************************************************************************************************
//*                      CODE GENERATED BY GenerateRuntimeItemBoringStuff tool!!!                         *
//*********************************************************************************************************
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xa0>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xa1>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xa2>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xa3>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xa4>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xa5>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xa6>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xa7>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xa8>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xa9>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xaa>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xab>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xac>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xad>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xae>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xaf>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xb0>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xb1>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xb2>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xb3>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xb4>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xb5>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xb6>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xb7>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xb8>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xb9>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xba>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xbb>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xbc>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xbd>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xbe>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	has<event_data>,
	empty<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xbf>;
//*********************************************************************************************************





} // namespace structure
} // namespace runtime
} // namespace rx_platform

