

/****************************************************************************
*
*  system\runtime\rx_rt_items4.cpp
*
*  Copyright (c) 2020-2023 ENSACO Solutions doo
*  Copyright (c) 2018-2019 Dusan Ciric
*
*
*  This file is part of {rx-platform}
*
*
*  {rx-platform} is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  {rx-platform} is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with {rx-platform}. It is also available in any {rx-platform} console
*  via <license> command. If not, see <http://www.gnu.org/licenses/>.
*
****************************************************************************/


#include "pch.h"



#include "system/runtime/rx_rt_item_types.cpp"

namespace rx_platform {
namespace runtime {
namespace structure {

//*********************************************************************************************************
//*                      CODE GENERATED BY GenerateRuntimeItemBoringStuff tool!!!                         *
//*********************************************************************************************************
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xd0>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xd1>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xd2>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xd3>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xd4>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xd5>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xd6>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xd7>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xd8>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xd9>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xda>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xdb>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xdc>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xdd>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xde>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	has<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xdf>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xc0>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xc1>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xc2>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xc3>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xc4>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xc5>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xc6>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	empty<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xc7>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xc8>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xc9>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xca>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	empty<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xcb>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xcc>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	empty<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xcd>;
template class runtime_data<
	empty<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xce>;
template class runtime_data<
	has<array_wrapper<variable_data>>,
	has<array_wrapper<struct_data>>,
	has<source_data>,
	has<mapper_data>,
	empty<filter_data>,
	empty<event_data>,
	has<array_wrapper<value_block_data>>,
	has<array_wrapper<variable_block_data>>,
	0xcf>;
//*********************************************************************************************************






} // namespace structure
} // namespace runtime
} // namespace rx_platform

